baseurl = "/"
languageCode = "en-us"
title = "付辉"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
    description = "蜗牛保持乐观才会爬的更远"
	author = "付辉"
    footer = "&copy; [Fu Hui](http://neojos.com) 2017 | [Github](https://github.com/GitHubSi) | [CSDN]()"

  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"